In [49]:
import pandas as pd
import numpy as np
import os
from sklearn import preprocessing

In [9]:
os.getcwd()

'/Users/mgb/Desktop/AI4SG/smrt/old_test_notebooks'

In [19]:
df1 = pd.read_csv("../datasets/luftklima_reformatted.csv")
df2 = pd.read_csv("../datasets/verkehrszählungen_reformatted.csv")

In [22]:
df1 = df1[df1.Datum == "2021-08-01"]

In [21]:
df2 = df2[df2.Date == "01.08.2021"]

In [24]:
drei2 = df2[df2["Geo Point"] == "47.5707346457,7.58226721123"]

In [33]:
drei2 = drei2.groupby("TimeFrom").sum()

In [28]:
drei1 = df1[df1.Name == "Dreirosenbrücke"]

In [30]:
len(drei1)

24

In [34]:
len(drei2)

24

In [35]:
drei2.head()

Unnamed: 0  Total  MR   PW  PW+  Lief  Lief+  Lief+Aufl.  LW  LW+  \
TimeFrom                                                                      
00:00        7305064    416   2  390    0    21      0           0   2    0   
01:00        7305344    289   1  270    0    18      0           0   0    0   
02:00        7305747    217   1  201    0    13      1           0   1    0   
03:00        7305993    179   1  164    0    14      0           0   0    0   
04:00        7306308    190   0  168    1    20      0           0   1    0   

          Sattelzug  Bus  andere   Year    Latitude  Longitude  
TimeFrom                                                        
00:00             0    1       0  10105  237.853673  37.911336  
01:00             0    0       0  10105  237.853673  37.911336  
02:00             0    0       0  10105  237.853673  37.911336  
03:00             0    0       0  10105  237.853673  37.911336  
04:00             0    0       0  10105  237.853673  37.911336

In [37]:
x1 = drei1.Lufttemperatur.tolist()

In [38]:
x2 = drei2.Total.tolist()

In [39]:
x1

[16.305,
 16.125,
 15.435,
 14.495,
 14.39,
 14.52,
 14.31,
 14.595,
 14.83,
 15.43,
 16.115,
 17.52,
 19.32,
 18.145,
 19.17,
 17.885,
 16.235,
 15.64,
 15.81,
 17.585,
 17.65,
 15.985,
 15.15,
 14.54]

In [42]:
test = np.array([x1, x2])

In [44]:
test.shape

(2, 24)

In [45]:
cov = np.cov(test)

In [46]:
cov

array([[2.32329561e+00, 3.29500607e+02],
       [3.29500607e+02, 7.41073460e+04]])

In [47]:
cov[0][1]

329.5006068840581

In [52]:
norm1 = preprocessing.normalize([np.array(x1)])

In [53]:
norm1

array([[0.2054273 , 0.20315948, 0.19446614, 0.18262305, 0.18130015,
        0.18293802, 0.18029222, 0.18388295, 0.18684372, 0.19440315,
        0.20303349, 0.22073513, 0.2434134 , 0.22860953, 0.24152354,
        0.22533378, 0.20454537, 0.19704894, 0.19919078, 0.22155407,
        0.22237301, 0.20139561, 0.19087541, 0.18319   ]])

In [54]:
norm2 = preprocessing.normalize([np.array(x2)])

In [56]:
norm1.shape

(1, 24)

In [58]:
stack = np.vstack([norm1, norm2])

In [59]:
stack

array([[0.2054273 , 0.20315948, 0.19446614, 0.18262305, 0.18130015,
        0.18293802, 0.18029222, 0.18388295, 0.18684372, 0.19440315,
        0.20303349, 0.22073513, 0.2434134 , 0.22860953, 0.24152354,
        0.22533378, 0.20454537, 0.19704894, 0.19919078, 0.22155407,
        0.22237301, 0.20139561, 0.19087541, 0.18319   ],
       [0.14718165, 0.10224879, 0.07677504, 0.06333057, 0.06722239,
        0.05908494, 0.07040661, 0.05342411, 0.08137447, 0.13692139,
        0.20520519, 0.25438367, 0.27455039, 0.28516445, 0.30533117,
        0.30073174, 0.32089846, 0.29082528, 0.28021122, 0.25473747,
        0.24553862, 0.20520519, 0.15779571, 0.10649442]])

In [60]:
stack.shape

(2, 24)

In [61]:
cov_norm = np.cov(stack)

In [62]:
cov_norm

array([[0.00036879, 0.00146877],
       [0.00146877, 0.00927645]])

In [63]:
cov_norm[0][1]

0.001468770427589472